from django.conf.urls import patterns, url
from fl import views
from florder import settings
urlpatterns = patterns('',
    url(r'^$', views.register, name='register'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^index/$', views.index),
    url(r'^show/$', views.show),
    url(r'^modify/$', views.modify),
    url(r'^showpwd/$', views.showpwd),
    url(r'^modifypwd/$', views.modifypwd),
    url(r'^adddish/$', views.adddish),
    url(r'^showdish/$', views.showdish),
    url(r'^deletedish/$', views.deletedish),
    url(r'^showmodifydish/$', views.showmodifydish),
    url(r'^modifydish/$', views.modifydish),
    url(r'^forgetpwd/$', views.forgetpwd),
    url(r'^sendpwdemail/$', views.sendpwdemail),
    url(r'^addtable/$', views.addtable),
    url(r'^showtable/$', views.showtable),
    url(r'^deletetable/$', views.deletetable),
    url(r'^fgpwdreset/$', views.fgpwdreset),
    url(r'^showresetpwd/$', views.showresetpwd),
    url(r'^resetpwd/$', views.resetpwd),
    url(r'^showuserphoto/$', views.showuserphoto),
    url(r'^resetuserphoto/$', views.resetuserphoto),
    url(r'^online/$', views.online),
    url(r'^subscribe/$', views.subscribe),
    url(r'^finishsubscribeorder/$', views.finishsubscribeorder),
    url(r'^history/$', views.history),
    url(r'^showfindorder/$', views.showfindorder),
    url(r'^finishorder/$', views.finishorder),
    url(r'^findorder/$', views.findorder),
    url(r'^showadddish/$', views.showadddish),
    url(r'^showaddtable/$', views.showaddtable),
    url(r'^checkname/((?:-|\w)+)/$', views.checkname),
    url(r'^checkemail/((?:-|\S)+)/$', views.checkemail),
    url(r'^checkdish/((?:-|\S)+)/$', views.checkdish),
    url(r'^print_order/$', views.print_order),
    #url(r'^qrcode/$', qrcode),
    #url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
)